name: CI Pipeline

on:
  push:
    branches: 
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v4

    - name: Build and Push
      run: |
        docker buildx create --driver-opt network=dev-net
        docker build -t 172.17.0.1:5000/examplevotingapp_vote:latest ./src/vote/ && docker push 172.17.0.1:5000/examplevotingapp_vote
        docker build -t 172.17.0.1:5000/examplevotingapp_worker:latest ./src/worker/ && docker push 172.17.0.1:5000/examplevotingapp_worker        
        docker build -t 172.17.0.1:5000/examplevotingapp_result:latest ./src/result/ && docker push 172.17.0.1:5000/examplevotingapp_result

  deploy-and-test:
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:latest

    steps:
    - name: Install Node.js
      run: |
        apk add nodejs npm
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy with Helm
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

        helm upgrade --install my-app ./kubernetes/helm/my-app --namespace my-app

    - name: Running test
      run: |
        sleep 10
        curl -H "Host: vote.local" http://k3s:8080
        curl -H "Host: result.local" http://k3s:8080
