{{- range .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  {{- if .depends_on }}
  initContainers:
  - name: wait-for-dependencies
    image: jwilder/dockerize
    command:
    - dockerize
    - -wait
    - tcp://postgres:5432
    - -wait
    - tcp://redis:6379
    - -timeout
    - 60s
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .env }}
          env:
          {{- .env | toYaml | nindent 12 }}
          {{- end }}
          {{- if .port }}
          ports:
            - containerPort: {{ .port }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- .volumeMounts | toYaml | nindent 12 }}
          {{- end }}
          {{- if .volumes }}
      volumes:
      {{- .volumes | toYaml | nindent 12 }}
      {{- end }}
{{- end }}