{{- range .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if .depends_on }}
      initContainers:
      - name: wait-for-dependencies
        image: jwilder/dockerize
        command:
        - dockerize
        - -wait
        - tcp://db:5432
        - -wait
        - tcp://redis:6379
        - -timeout
        - 30s
      {{- end }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag | default "latest" }}
          {{- if .env }}
          env:
          {{- .env | toYaml | nindent 12 }}
          {{- end }}
          {{- if .port }}
          ports:
            - containerPort: {{ .targetPort }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .targetPort }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- .volumeMounts | toYaml | nindent 12 }}
          {{- end }}
          {{- if .volumes }}
      volumes:
      {{- .volumes | toYaml | nindent 12 }}
      {{- end }}
{{- end }}