{{- range .Values.applications }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .name }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .name }}
{{- end }}