{{- range .Values.applications }}
{{- if .service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  type: ClusterIP
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
{{- end }}
{{- end }}