replicaCount: 1

image:
  repository: registry:5000/birthday
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

ingress:
  host: app.local
  http:
    path: /
    type: Prefix