replicaCount: 2

applications:
  - name: vote
    service: true
    ingress: true
    image: pota2chess/examplevotingapp_vote
    tag: latest
    port: 8080
    targetPort: 80
    host: vote.local
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      requests: { cpu: "10m", memory: "150Mi" }
      limits: { cpu: "20m", memory: "300Mi" }

  - name: redis
    service: true
    ingress: false
    image: redis
    tag: alpine
    port: 6379
    targetPort: 6379
    volumeMounts:
    - mountPath: /data
      name: redis-data
    volumes:
    - name: redis-data
      emptyDir: {}
    resources:
      requests: { cpu: "15m", memory: "40Mi" }
      limits: { cpu: "30m", memory: "80Mi" }

  - name: worker
    service: false
    ingress: false
    image: pota2chess/examplevotingapp_worker
    tag: latest
    depends_on:
    - name: db
      port: 5432
    - name: redis
      port: 6379
    resources:
      requests: { cpu: "15m", memory: "70Mi" }
      limits: { cpu: "30m", memory: "140Mi" }

  - name: db
    service: true
    ingress: false
    image: postgres
    tag: 15-alpine
    port: 5432
    targetPort: 5432
    env:
    - name: POSTGRES_USER
      value: posgtres
    - name: POSTGRES_PASSWORD
      value: posgtres
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-data
    volumes:
    - name: db-data
      emptyDir: {}
    resources:
      requests: { cpu: "15m", memory: "70Mi" }
      limits: { cpu: "30m", memory: "140Mi" }

  - name: result
    service: true
    ingress: true
    image: pota2chess/examplevotingapp_result
    tag: latest
    port: 8081
    targetPort: 80
    host: result.local
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      requests: { cpu: "10m", memory: "70Mi" }
      limits: { cpu: "20m", memory: "140Mi" }